version: 2.0.{build}

branches:
  only:
    - Master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

#before_build:
#  - nuget restore
  
build:
  project: DotNetProjects.PrintEngine\DotNetProjects.PrintEngine.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: DotNetProjects.PrintEngine\bin\Debug\DotNetProjects.PrintEngine.dll
    name: DotNetProjects.PrintEngine.dll
  - path: DotNetProjects.PrintEngine\bin\Debug\DotNetProjects.PrintEngine.pdb
    name: DotNetProjects.PrintEngine.pdb
  - path: '**\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  